check2<-check2 %>% 
  rename(SEI_LOCATION_HISTORY_ID=EVENT_LMAS_LOCATION_HISTORY_ID,
         SEI_EVENT_LMAS_SAMPLE_DATE=EVENT_LMAS_SAMPLE_DATE,
         SEI_EVENT_LMAS_PROJECT_CDE=EVENT_LMAS_PROJECT_CDE,
         SEI_EVENT_LMAS_DATA_PROVIDER=EVENT_LMAS_DATA_PROVIDER,
         SEI_EVENT_LMAS_SAMPLE_TIME=EVENT_LMAS_SAMPLE_TIME) %>% 
  mutate(SEI_EVENT_LMAS_SAMPLE_DATE=as.Date(SEI_EVENT_LMAS_SAMPLE_DATE,format="%m/%d/%Y"))
  
check3<-merge(check2,SEI,by=c('SEI_LOCATION_HISTORY_ID','SEI_EVENT_LMAS_SAMPLE_DATE','SEI_EVENT_LMAS_PROJECT_CDE','SEI_EVENT_LMAS_DATA_PROVIDER','SEI_EVENT_LMAS_SAMPLE_TIME'),all.x = TRUE)

